# -*- coding: utf-8 -*-
"""Strepitus Silvae.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dp3ZSKLwP664ugHFWWSUSv1aubA6-ChY
"""

# 1. Instalar la librería (Colab no la trae por defecto)
!pip install openai -q
!pip install pyinaturalist

import base64
import json
from google.colab import files, userdata
from openai import OpenAI
import getpass

from pyinaturalist import get_taxa

api_key = userdata.get('openai_api_key')

client = OpenAI(api_key=api_key)

# 3. Subir la imagen de prueba
print("\nSube una imagen de cámara trampa para la prueba:")
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

# 4. Función para codificar la imagen en Base64
def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

base64_image = encode_image(image_path)

# 5. El System Prompt: Aquí está la magia del contexto ecológico
system_prompt_old = """
Eres un biólogo experto en monitoreo de fauna silvestre.
Analiza la siguiente imagen de una cámara trampa y extrae los datos ecológicos en formato JSON.
Tu respuesta debe ser estrictamente un JSON válido con la siguiente estructura:
{
  "especie_identificada": "Nombre común o científico",
  "numero_individuos": 1,
  "comportamiento": "Breve descripción de lo que está haciendo (ej. forrajeando, en movimiento, alerta)",
  "salud_aparente": "Observaciones sobre plumaje, pelaje o estado físico visible",
  "alerta_humana_o_vehiculo": boolean (true si hay presencia humana o vehículos, false si no),
  "nivel_confianza": "alto, medio, bajo"
}
"""


SYSTEM_PROMPT = """
Eres un biólogo experto en conservación y ecología de campo en América Latina.
Tu tarea es analizar fotografías de cámaras trampa (fototrampeo) y extraer datos ecológicos detallados. Las imágenes pueden ser nocturnas, borrosas o en blanco y negro (infrarrojo).

REGLAS ESTRICTAS:
1. No inventes especies. Si la imagen es demasiado confusa, proporciona la familia o género más probable y marca la confianza como "bajo".
2. Tu respuesta debe ser ÚNICA y EXCLUSIVAMENTE un objeto JSON válido. No incluyas texto antes ni después del JSON. No uses bloques de código (```json) en la salida.

ESTRUCTURA DEL JSON REQUERIDO:
{
  "especie_identificada": "Nombre común (Nombre científico)",
  "numero_individuos": <entero>,
  "comportamiento": "Descripción breve y clínica de la actividad (ej. forrajeando, desplazándose, alerta, reposo)",
  "salud_aparente": "Observación sobre la condición corporal visible, pelaje o plumaje. Si no es visible, escribe 'No evaluable por calidad de imagen'",
  "alerta_humana_o_vehiculo": <booleano true/false>,
  "nivel_confianza": "<'alto', 'medio', o 'bajo'>"
}

CRITERIOS DE CONFIANZA:
- "alto": Identificación inequívoca de la especie.
- "medio": Especie probable, pero la iluminación, distancia o ángulo impiden total certeza.
- "bajo": Solo se puede identificar a nivel de familia/género, o la imagen es extremadamente ambigua.
"""

print("\nAnalizando la imagen con OpenAI Vision... espera un momento.")
response = client.chat.completions.create(
  model="gpt-5.6-luna",
  response_format={ "type": "json_object" },
  messages=[
    {
      "role": "system",
      "content": system_prompt
    },
    {
      "role": "user",
      "content": [
        {
          "type": "image_url",
          "image_url": {
            "url": f"data:image/jpeg;base64,{base64_image}"
          }
        }
      ]
    }
  ]
)

# 7. Mostrar el resultado
resultado_json = response.choices[0].message.content
print("\n--- RESULTADO ESTRUCTURADO ---")
print(json.dumps(json.loads(resultado_json), indent=2, ensure_ascii=False))

def validar_con_naturalista(nombre_especie):
    """
    Consulta la API de iNaturalist para validar si la especie sugerida por GPT existe
    y obtiene su nomenclatura científica oficial.
    """
    print(f"🔍 [Agente iNat] Validando '{nombre_especie}' en la base de datos externa...")

    try:
        # Buscamos coincidencias de la especie (q=query)
        respuesta = get_taxa(q=nombre_especie, rank=['species', 'subspecies'])
        resultados = respuesta.get('results', [])

        if resultados:
            # Tomamos la mejor coincidencia
            taxon = resultados[0]
            return {
                "validacion_exitosa": True,
                "nombre_cientifico_oficial": taxon.get('name'),
                "nombre_comun_inaturalist": taxon.get('preferred_common_name', 'No disponible'),
                "id_taxonomico": taxon.get('id')
            }
        else:
            return {"validacion_exitosa": False, "mensaje": "Especie no encontrada en iNaturalist"}

    except Exception as e:
        return {"error": str(e)}

# --- CÓMO SE INTEGRA EN TU FLUJO PRINCIPAL ---
# Suponiendo que 'resultado_json' es el texto que te devolvió OpenAI Vision:

datos_gpt = json.loads(resultado_json)

# Evaluamos la confianza como un verdadero agente autónomo
if datos_gpt.get("nivel_confianza") in ["medio", "bajo"]:
    print("⚠️ Confianza media/baja detectada. Activando protocolo de validación cruzada.")

    especie_sugerida = datos_gpt.get("especie_identificada")
    datos_validacion = validar_con_naturalista(especie_sugerida)

    # Inyectamos los nuevos datos validados al JSON original
    datos_gpt["validacion_externa"] = datos_validacion

print("\n--- REGISTRO FINAL (LISTO PARA LA BASE DE DATOS) ---")
print(json.dumps(datos_gpt, indent=2, ensure_ascii=False))